---
title: "課?<a0>?練習模<e7><89><88>"
author: "Ruiyi"
date: "2020-10-07"
output: output_format
params:
  id: "410781027"
---




```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```

```{r}
vNum1 <- vNum2
vNum2 <- c(2,vNum1)
```

## Your code

```{r}
heightOfAStudentComingInsideTheClassroom <- sample(165:200,1)
```


```{r}
# method 1: concatenate 
heightsOftheEntireClassroom <-
  c(
    heightsOftheEntireClassroom,
    heightOfAStudentComingInsideTheClassroom
  )
```


```{r}
# method 2: 
heightsOftheEntireClassroom2 <-
  heightOfAStudentComingInsideTheClassroom
```





```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7) #會預留空間給小數點
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1)
typeof(num2)
```

```{r}
char1<-"你好"
char2<-'你好'
```

```{r}
char1Vector<-c("你好","How are you?")
```

```{r}
class(char2)
```
```{r}
dialogue <- '小明說："明天不用上課。" '
```


```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

dialogue # 顯示原始值的內容（含輸入時的引號）
cat(dialogue, sep="\n") # 顯示給人類看（含存出來）的值，sep="\n", 不同元素換行陳列。
writeLines(dialogue, "conversation.txt") # cat顯示的正是存出來樣貌。
```

```{r}
context <- "老師說換行要寫\\n"
cat(context)
```

